url: "https://akrog.dev"
baseurl: "/"
title: "George Pitarch"

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  notes:
    output: true
    permalink: /:collection/:slug
    sort_by: updated_at || published_at
